name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: oooiooop9988/db
          stage: main
          yaml: |
            name: likelion-13th-swu-festival-be
            app: java@17
            options:
              ports: "8080"
              env:
                - name: SPRING_PROFILES_ACTIVE
                  value: dev
                - name: DEV_DB_USERNAME
                  value: root
                - name: DEV_DB_PASSWORD
                  value: "20020622"
                - name: DEV_DB_URL
                  value: jdbc:mariadb://svc.sel4.cloudtype.app:31846/festival
                - name: DB_USERNAME
                  value: root
                - name: DB_PASSWORD
                  value: "98653232"
                - name: DB_URL
                  value: jdbc:mysql://localhost:3306/festival
              buildenv: []
            context:
              git:
                url: https://github.com/${{ github.repository }}.git
                ref: ${{ github.ref }}
